// Service Categories for LOCALAI
import { ServiceCategory } from '../db/types';

export const SERVICE_CATEGORIES: ServiceCategory[] = [
  {
    id: 'cat-ac-repair',
    name: 'AC Repair & Service',
    teluguName: 'AC రిపేర్ & సర్వీస్',
    slug: 'ac-repair',
    icon: 'Snowflake',
    description: 'AC cooling issues, gas refilling, filter cleaning, installation and servicing',
    teluguDescription: 'కూలింగ్ సమస్యలు, గ్యాస్ రీఫిల్, జెట్ పంప్ క్లీనింగ్ మరియు ఇన్‌స్టాలేషన్',
    subcategories: ['Not Cooling', 'Gas Leakage / Refill', 'Deep Cleaning / Service', 'Installation / Uninstallation', 'Water Leakage', 'Noise / Electrical Fault'],
    basePriceEstimate: 399,
    popular: true,
  },
  {
    id: 'cat-electrician',
    name: 'Electrician',
    teluguName: 'ఎలక్ట్రీషియన్ (విద్యుత్ పనులు)',
    slug: 'electrician',
    icon: 'Zap',
    description: 'Switchboard wiring, fan repair, inverter fixing, fuse issues, short circuit repairs',
    teluguDescription: 'స్విచ్ బోర్డులు, ఫ్యాన్లు, ఇన్వర్టర్ వైరింగ్ మరియు షార్ట్ సర్క్యూట్ రిపేర్లు',
    subcategories: ['Switchboard & Socket Repair', 'Ceiling Fan Repair / Installation', 'Inverter / Battery Wiring', 'MCB / Fuse Tripping', 'House Wiring / Rewiring', 'Geyser Electrical Repair'],
    basePriceEstimate: 199,
    popular: true,
  },
  {
    id: 'cat-plumber',
    name: 'Plumber',
    teluguName: 'ప్లంబర్ (నీటి పైపుల పనులు)',
    slug: 'plumber',
    icon: 'Droplets',
    description: 'Tap leakage, pipe blockage, motor installation, flush repair, sanitary fittings',
    teluguDescription: 'నల్లా లీకేజ్, పైపు బ్లాకేజ్, వాటర్ మోటార్ మరియు ట్యాంక్ కనెక్షన్లు',
    subcategories: ['Tap Repair / Replacement', 'Pipe Blockage & Drainage', 'Water Motor Pump Repair', 'Toilet Flush / Commode Leak', 'Water Tank Cleaning / Piping', 'Shower & Bathroom Fitting'],
    basePriceEstimate: 199,
    popular: true,
  },
  {
    id: 'cat-refrigerator',
    name: 'Refrigerator Repair',
    teluguName: 'ఫ్రిజ్ రిపేర్ (రిఫ్రిజిరేటర్)',
    slug: 'refrigerator-repair',
    icon: 'ThermometerSnowflake',
    description: 'Fridge not cooling, compressor problem, ice buildup, gas charge, thermostat',
    teluguDescription: 'ఫ్రిజ్ కూలింగ్ రాకపోవడం, కంప్రెసర్ మరియు గ్యాస్ లీకేజ్ సమస్యలు',
    subcategories: ['Fridge Not Cooling', 'Compressor Issue', 'Excessive Ice Frosting', 'Gas Leakage / Refill', 'Power / Wiring Issue', 'Door Seal / Sensor Fault'],
    basePriceEstimate: 349,
    popular: true,
  },
  {
    id: 'cat-washing-machine',
    name: 'Washing Machine Repair',
    teluguName: 'వాషింగ్ మెషిన్ సర్వీస్',
    slug: 'washing-machine-repair',
    icon: 'Disc',
    description: 'Drum not spinning, water not draining, error codes, heavy vibration, motor issue',
    teluguDescription: 'డ్రమ్ తిరగకపోవడం, నీరు బయటకు పోకపోవడం, అధిక శబ్దం మరియు వైబ్రేషన్',
    subcategories: ['Drum Not Spinning', 'Water Not Draining', 'Front / Top Load Error Code', 'Vibration & Loud Noise', 'Water Leakage', 'Motherboard / Motor Issue'],
    basePriceEstimate: 349,
    popular: true,
  },
  {
    id: 'cat-tv-repair',
    name: 'TV Repair & Mounting',
    teluguName: 'టీవీ రిపేర్ & వాల్ మౌంటింగ్',
    slug: 'tv-repair',
    icon: 'Tv',
    description: 'LED/Smart TV display issue, sound problem, wall mounting, HDMI port repair',
    teluguDescription: 'స్మార్ట్ టీవీ డిస్‌ప్లే లైన్లు, సౌండ్ సమస్యలు మరియు వాల్ మౌంట్ ఫిట్టింగ్',
    subcategories: ['Screen / Display Blank or Lines', 'Sound But No Video', 'Wall Mounting Installation', 'Power Board Repair', 'Backlight Replacement'],
    basePriceEstimate: 299,
    popular: false,
  },
  {
    id: 'cat-computer-repair',
    name: 'Computer & Laptop Repair',
    teluguName: 'కంప్యూటర్ & ల్యాప్‌టాప్ రిపేర్',
    slug: 'computer-repair',
    icon: 'Laptop',
    description: 'OS formatting, slow speed, screen replacement, virus cleaning, RAM/SSD upgrade',
    teluguDescription: 'విండోస్ ఫార్మాటింగ్, స్లో స్పీడ్, డిస్‌ప్లే మార్పు మరియు వైరస్ క్లీనింగ్',
    subcategories: ['Windows / OS Formatting', 'SSD / RAM Upgrade', 'Laptop Screen / Keyboard Replacement', 'Slow Performance / Virus Removal', 'Motherboard Chip Level Repair'],
    basePriceEstimate: 399,
    popular: false,
  },
  {
    id: 'cat-mobile-repair',
    name: 'Mobile Phone Repair',
    teluguName: 'మొబైల్ ఫోన్ రిపేర్',
    slug: 'mobile-repair',
    icon: 'Smartphone',
    description: 'Broken display, battery replacement, charging pin issue, mic/speaker problem',
    teluguDescription: 'పగిలిన స్క్రీన్, బ్యాటరీ మార్పు, ఛార్జింగ్ పిన్ మరియు స్పీకర్ రిపేర్',
    subcategories: ['Screen / Glass Replacement', 'Battery Drain / Replacement', 'Charging Port / Pin Repair', 'Speaker / Mic Audio Issue', 'Water Damage Recovery'],
    basePriceEstimate: 299,
    popular: false,
  },
  {
    id: 'cat-bike-mechanic',
    name: 'Bike Mechanic',
    teluguName: 'బైక్ మెకానిక్ (డోర్‌స్టెప్)',
    slug: 'bike-mechanic',
    icon: 'Bike',
    description: 'Doorstep bike servicing, engine oil change, puncture/tubeless repair, brake repair',
    teluguDescription: 'ఇంటి వద్దే బైక్ సర్వీస్, ఆయిల్ చేంజ్, బ్రేక్ వైరింగ్ మరియు పంచర్ రిపేర్',
    subcategories: ['General Service & Oil Change', 'Puncture & Tyre Check', 'Brake Pad / Cable Replacement', 'Self Start / Battery Issue', 'Chain Sprocket / Clutch Repair'],
    basePriceEstimate: 249,
    popular: true,
  },
  {
    id: 'cat-car-mechanic',
    name: 'Car Mechanic',
    teluguName: 'కార్ మెకానిక్ & బ్రేక్‌డౌన్',
    slug: 'car-mechanic',
    icon: 'Car',
    description: 'Breakdown help, battery jumpstart, brake service, AC gas, engine checkup',
    teluguDescription: 'రోడ్డుపై బ్రేక్‌డౌన్ సహాయం, బ్యాటరీ జంప్‌స్టార్ట్, బ్రేక్ మరియు AC సర్వీస్',
    subcategories: ['Battery Jumpstart', 'Car Breakdown / Towing Advice', 'Brake Service & Inspection', 'Car AC Gas & Cooling', 'Oil Change & Filter Service'],
    basePriceEstimate: 499,
    popular: false,
  },
  {
    id: 'cat-carpenter',
    name: 'Carpenter',
    teluguName: 'కార్పెంటర్ (చెక్క పనులు)',
    slug: 'carpenter',
    icon: 'Hammer',
    description: 'Door lock fixing, furniture repair, cupboards, hinges, customized woodwork',
    teluguDescription: 'డోర్ లాక్స్, కప్‌బోర్డ్స్, మంచాలు మరియు ఫర్నిచర్ రిపేర్ పనులు',
    subcategories: ['Door Lock & Handle Repair', 'Bed / Wardrobe Repair', 'Hinges & Slider Adjustment', 'Custom Shelving & Woodwork', 'Mesh / Mosquito Net Door Fitting'],
    basePriceEstimate: 249,
    popular: false,
  },
  {
    id: 'cat-painter',
    name: 'Painter',
    teluguName: 'పెయింటర్ (రంగులు & పుట్టీ)',
    slug: 'painter',
    icon: 'Paintbrush',
    description: 'Interior & exterior wall painting, waterproof coating, touchups, putty finish',
    teluguDescription: 'ఇంటి లోపల మరియు బయట గోడల పెయింటింగ్, వాటర్‌ప్రూఫింగ్ కోటింగ్',
    subcategories: ['Room Painting', 'Waterproofing & Damp Repair', 'Exterior Wall Painting', 'Wood Polish & Door Enamel', 'Texture & Wallpaper Design'],
    basePriceEstimate: 799,
    popular: false,
  },
  {
    id: 'cat-cleaning',
    name: 'Home Cleaning',
    teluguName: 'డీప్ క్లీనింగ్ (ఇంటి శుభ్రత)',
    slug: 'cleaning',
    icon: 'Sparkles',
    description: 'Deep house cleaning, bathroom scrubbing, sofa shampooing, kitchen chimney cleaning',
    teluguDescription: 'పూర్తి ఇల్లు క్లీనింగ్, బాత్రూమ్ క్లీనింగ్, సోఫా వాష్ మరియు కిచెన్ చిమ్నీ',
    subcategories: ['Deep Bathroom Cleaning', 'Full Home Deep Cleaning', 'Sofa & Mattress Shampoo', 'Kitchen Chimney & Tile Degreasing', 'Floor Polishing & Scrubbing'],
    basePriceEstimate: 499,
    popular: true,
  },
  {
    id: 'cat-cctv',
    name: 'CCTV Installation & Service',
    teluguName: 'CCTV కెమెరా ఫిట్టింగ్ & సర్వీస్',
    slug: 'cctv-installation',
    icon: 'Camera',
    description: 'Security camera setup, DVR/NVR configuration, mobile app view, camera repair',
    teluguDescription: 'కొత్త CCTV కెమెరాలు అమర్చడం, DVR సెటప్ మరియు మొబైల్ కనెక్షన్',
    subcategories: ['New CCTV Camera Installation', 'DVR / Hard Disk Setup', 'Mobile Remote View Config', 'Camera Blur / Offline Fixing', 'Wiring & Power Adapter Repair'],
    basePriceEstimate: 499,
    popular: false,
  },
  {
    id: 'cat-wifi-network',
    name: 'Internet & Wi-Fi Setup',
    teluguName: 'ఇంటర్నెట్ & వై-ఫై సెటప్',
    slug: 'internet-wifi-setup',
    icon: 'Wifi',
    description: 'Wi-Fi router configuration, range extender setup, LAN cable crimping, optic fiber',
    teluguDescription: 'వై-ఫై రౌటర్ కాన్ఫిగరేషన్, రేంజ్ ఎక్స్‌టెండర్ మరియు ఇంటర్నెట్ కేబుల్ పనులు',
    subcategories: ['Wi-Fi Router Setup & Range Extender', 'LAN Cable Crimping & Wiring', 'Mesh Wi-Fi Installation', 'Internet Speed & Port Troubleshooting'],
    basePriceEstimate: 299,
    popular: false,
  },
  {
    id: 'cat-pest-control',
    name: 'Pest Control',
    teluguName: 'పెస్ట్ కంట్రోల్ (చీడపీడల నివారణ)',
    slug: 'pest-control',
    icon: 'ShieldAlert',
    description: 'Cockroach gel treatment, termite protection, bed bug control, mosquito spray',
    teluguDescription: 'బొద్దింకలు, చెదపురుగులు, నల్లుల నివారణకు హెర్బల్ ట్రీట్‌మెంట్',
    subcategories: ['Cockroach Herbal Gel Treatment', 'Termite Anti-Borer Drill & Fill', 'Bed Bug Heat / Chemical Spray', 'Ant & Rodent Elimination'],
    basePriceEstimate: 699,
    popular: false,
  },
  {
    id: 'cat-moving',
    name: 'Packers & Movers',
    teluguName: 'ప్యాకర్స్ & మూవర్స్ (ఇల్లు మార్పు)',
    slug: 'packers-movers',
    icon: 'Truck',
    description: 'Local house shifting within Chilakaluripet or nearby towns, furniture loading',
    teluguDescription: 'చిలకలూరిపేట మరియు సమీప ప్రాంతాలలో ఇల్లు లేదా షాపు మార్పిడి సహాయం',
    subcategories: ['Local House Shifting (1-2 BHK)', 'Heavy Furniture & Appliance Moving', 'Single Item Delivery / Loading', 'Office & Shop Relocation'],
    basePriceEstimate: 1499,
    popular: false,
  },
];
